Ideal.Web/Areas/User/Controllers/IdeasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ideal.Services;
using Ideal.Services.Implementations;
using Ideal.Services.Models;
using Ideal.Web.Areas.User.Models;
using Ideal.Web.Controllers;
using Ideal.Web.Infrastructure.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace Ideal.Web.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    public class IdeasController : Controller
    {
        private readonly UserManager<Ideal.Data.Models.User> _userManager;
        private readonly IIdeaService ideas;
        private readonly ITeamService teams;
        private readonly IUserService users;
        private const int IdeaPageSize = 8;

        public IdeasController(UserManager<Ideal.Data.Models.User> userManager,IIdeaService ideas,
            ITeamService teams, IUserService users)
        {
            this._userManager = userManager;
            this.ideas = ideas;
            this.teams = teams;
            this.users = users;
        }

        public async Task<IActionResult> Index(int page=1)
        {
            return View(new IdeaListingViewModel()
            {
                Ideas = await this.ideas.ActiveAsyncApproved(page,IdeaPageSize),
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling(this.ideas.TotalApproved()/(double)IdeaPageSize)
            });
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AddingIdeaModel model)
        {
            if (!ModelState.IsValid)
            {                
                return View(model);
            }
            try
            {
                await this.teams.CreateAsync(
                    model.TeamName,
                    model.Teamsize,
                    _userManager.GetUserId(HttpContext.User)
                );

                await this.ideas.CreateAsync(
                    model.Name,
                    model.Description,
                    model.TeamName,
                    model.Teamsize,
                    _userManager.GetUserId(HttpContext.User)
                );


                TempData.AddSuccessMessage($"Idea {model.Name} and Team {model.TeamName} created successfully!");

                return RedirectToAction(
                    nameof(HomeController.Index),
                    "Home",
                    new { area = string.Empty });
            }
            catch (Exception e)
            {
                TempData.AddErrorMessage($"Team Name or Idea Name already exist");
                return View(model);
            }
            
        }

        public async Task<IActionResult> Details(int id)
        {
            var idea = new IdeaDetailsViewModel()
            {
                Idea = await this.ideas.ByIdAsync(id)
            };
            if (idea.Idea.Participants.Any(p => p == _userManager.GetUserName(HttpContext.User)) ||
                idea.Idea.Participants.Count == idea.Idea.Teamsize)
            {
                idea.Idea.SignUp = false;
            }
            else
            {
                idea.Idea.SignUp = true;

            }

            return View(idea);
        }

        public async Task<IActionResult> SignUp(string name)
        {
            await this.users.CreateAsync(
                name,
                _userManager.GetUserId(HttpContext.User)
            );

            
            TempData.AddSuccessMessage($"SignUp was  successfully!");

            return RedirectToAction(
                nameof(HomeController.Index),
                "Home",
                new { area = string.Empty });
        }
    }
}

Ideal.Web/Areas/User/Views/Ideas/Create.cshtml
@model AddingIdeaModel

@{
    ViewData["Title"] = "Create Idea";
}
<h2>@ViewData["Title"]</h2>
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" rows="10" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TeamName"></label>
                <input asp-for="TeamName" class="form-control" />
                <span asp-validation-for="TeamName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Teamsize"></label>
                <<input type="number" asp-for="Teamsize" class="form-control" value="0"/>
            </div>
            <button type="submit" class="btn btn-default">Add Idea</button>
        </form>
    </div>
</div>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Ideal.Web/Areas/User/Views/Ideas/Details.cshtml
@model IdeaDetailsViewModel
@{
    ViewData["Title"] = "Details";
}

<div class="row panel panel-success" style="margin-top:2%;">
    <div class="panel-heading lead">
        <div class="row">
            <div class="col-lg-8 col-md-8">View @Model.Idea.Name Details</div>           
        </div>
    </div>
    <div class="panel-body">



        <div class="row">
            <div class="col-lg-12 col-md-12">

                <div class="row">
                    <div class="col-lg-3 col-md-3">
                        <center>
                            <span class="text-left">



                            </span>
                        </center>

                        <div class="table-responsive panel">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td class="text-center">
                                            @if (Model.Idea.SignUp)
                                            {
                                                <a  class="btn btn-success btn-block"asp-controller="Ideas" asp-action="SignUp" asp-route-name="@Model.Idea.TeamName"> Sign up</a>
                                            }
                                        </td>
                                    </tr>

                                </tbody>
                            </table>
                        </div>


                    </div>
                    <div class="col-lg-9 col-md-9">
                        <ul class="nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="#Summery" class="text-success"> Summery</a></li>
                            <li><a data-toggle="tab" href="#Description" class="text-success">Description</a></li>  
                            <li><a data-toggle="tab" href="#TeamMembers" class="text-success">TeamMembers</a></li>                            

                        </ul>

                        <div class="tab-content">
                            <div id="Summery" class="tab-pane fade in active">

                                <div class="table-responsive panel">
                                    <table class="table">
                                        <tbody>

                                            <tr>
                                                <td class="text-success">Idea Name</td>
                                                <td>@Model.Idea.Name</td>
                                            </tr>
                                            <tr>
                                                <td class="text-success">Team Name</td>
                                                <td>@Model.Idea.TeamName</td>
                                            </tr>
                                            <tr>
                                                <td class="text-success">IdeaCreator Name</td>
                                                <td>@Model.Idea.IdeaOwner</td>
                                            </tr>
                                            <tr>
                                                <td class="text-success">Team size</td>
                                                <td>@Model.Idea.Participants.Count/@Model.Idea.Teamsize</td>
                                            </tr>                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                            <div id="Description" class="tab-pane fade">
                                <div class="table-responsive panel">
                                    @Model.Idea.Description
                                </div>
                            </div>
                            

                                <div id="TeamMembers" class="tab-pane fade in active">

                                    <div class="table-responsive panel">
                                        <table class="table">
                                            <tbody>
                                            @foreach (var participant in Model.Idea.Participants)
                                            {
                                                <tr>
                                                    <td class="text-success">Name</td>
                                                    <td>@participant</td>
                                                </tr>
                                            }
                                            
                                                                                
                                            </tbody>
                                        </table>
                                    </div>
                            

                        </div>

                    </div>

                </div>
            </div>
        </div>
        <!-- /.table-responsive -->

    </div>
    </div>
</div>

Ideal.Web/Areas/User/Views/Ideas/Index.cshtml
@model IdeaListingViewModel
@{
    ViewData["Title"] = "Ideas";
}

<div class="container">
    <div class="head_title text-center">
        <h1>Our Ideas Platform</h1>
    </div>
    <ul class="pagination">
        <li class="page-item">
            @if (Model.CurrentPage != 1)
            {
                <a class="page-link" href="/user/ideas?page=@Model.PreviousPage" aria-label="Previous">
                    <span aria-hidden="true">«</span>
                    <span class="sr-only">Previous</span>
                </a>
            }
        </li>
        @for (int i = 1; i <= Model.TotalPages; i++)
        {
            <li class="page-item"><a class="page-link" href="/user/ideas?page=@i">@i</a></li>
        }
    @if (Model.CurrentPage != Model.TotalPages)
    {
        <li class="page-item">
            <a class="page-link" href="/user/ideas?page=@Model.NextPage" aria-label="Next">
                <span aria-hidden="true">»</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    }
    </ul>
    <div class="row">
        <div class="portfolio-wrapper text-center">
                @await Html.PartialAsync("_IdeaListingPartial", Model.Ideas)
        </div>
    </div>
</div>

Ideal.Web/Areas/User/Views/Ideas/_IdeaListingPartial.cshtml
@model IEnumerable<Ideal.Services.Models.IdeaListingModelService>

@foreach (var idea in Model)
{
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="community-edition" border-radius: 25px>
            <i class="fa fa-lightbulb-o" aria-hidden="true"></i>
            <div class="separator"></div>
            <h4 class="ideaname">@idea.Name</h4>
            <a class="btn btn-primary" asp-controller="Ideas" asp-action="Details" asp-route-id="@idea.Id">Details</a>
        </div>
    </div>
}